### ISSUE TITLE
not  use merchant id in env

### ISSUE THREAD

**Issue by shdehnavi** [Saeed-Pooyanfar/zarinpal-laravel#14]
hi
i want to define merchant id in request function, i have many merchant id's for reasons, any way ?

**Comment by Saeed-Pooyanfar** [comment]
```php
<?php

namespace Zarinpal;
...
class Zarinpal
{
...
public string $merchantID;
...
}
```
Hi
`$merchantID` is a public prop of Zarinpal\Zarinpal class,
So you can easily change it anywhere base on your need

**Comment by ohmydevops** [comment]
این ایشو رو به نظر میشه بست @Saeed-Pooyanfar
