### ISSUE TITLE
خطای CORS

### ISSUE THREAD

**Issue by tmediaa** [Saeed-Pooyanfar/zarinpal-laravel#4]
سلام  من این پکیح رو تو پروژه لاراولی که دارم و قسمت فرانتش رو با vue نوشتم استفاده کردم
مشکلی که هست اینه که موقع درخواست از سمت کاربر به سمت کنترلر ارتباط با زرین پال خطای CORS دریافت میشه
میخواستم ببینم این مشکل روباید چجوری حل کنم
من حتی از پکیج laravel-cors هم استفاده کردم
البته این رو هم عرض کنم من الان پروژه رو روی لوکال تست میکنم

**Comment by Saeed-Pooyanfar** [comment]
Hi, use SoapClient for local test
