### ISSUE TITLE
after install in composer ,  how publish

### ISSUE THREAD

**Issue by HamidReazaNikoonia** [Saeed-Pooyanfar/zarinpal-laravel#5]
سلام ممنون بابت کار خوبی که کردید و حتما بابتش زحمت کشیدید
من توی لاراول تازه کار هستم ، تا اونجایی که من میدونم همیشه بعد از نصب یک پکیج با 
composer
بعدش باید اون رو
publish 
کنم ، اما من توی داکیومنت های شما همچین چیزی رو ندیدم ، آیا نیاز هست به این کار یا نه
و اگر که نیاز هست دقیقا باید چی توی ترمینال وارد کنم
ممنون میشم اگر پاسخ بنده رو بدید

**Comment by HamidReazaNikoonia** [comment]
و همینطور این که آیا من میتونم توی لوکال هاست یک تست انجام بدم و
Request 
بفرستم
و همینطور من توی فایل 
app.php
بعد از اضافه کردن 
provider
شورتکاتی براش درست نکردم 
حالا میتونم از این کد استفاده کنم 
use Zarinpal\Zarinpal;

**Comment by Obka** [comment]
@HamidReazaNikoonia سلام
پس از نصب دستور ذیل وارد شود .

`php artisan vendor:publish --provider=Zarinpal\ZarinpalServiceProvider`

**Comment by amirbagh75** [comment]
برای نسخه جدید لاراول هشت این موضوع خودکار میشه و دیگه نیازی به این کار نیست
 (https://github.com/Saeed-Pooyanfar/zarinpal-laravel/blob/5382f07bb7edb5ad1d8409e393b7f7321bc76cd6/composer.json#L24)

**Comment by ohmydevops** [comment]
این ایشو رو به نظر میشه بست @Saeed-Pooyanfar
